---
# file: tasks/debug.yml
#
# debug tasks.
#

- debug:
    var="{{ item }}"
  when: "{{ item }} is defined"
  with_items:
    - ansible_distribution
    - ansible_distribution_release
    - influxdb_admin_port
    - influxdb_apt_dependencies
    - influxdb_conf_file
    - influxdb_group
    - influxdb_http_port
    - influxdb_user

