---
# file: influxdb/tasks/validation.yml
#
# validation tasks.
#

- name: ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - influxdb_admin_port
    - influxdb_conf_file
    - influxdb_group
    - influxdb_http_port
    - influxdb_user

